// <auto-generated />
using System;
using KlopZavod.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KlopZavod.Migrations
{
    [DbContext(typeof(ZavodContext))]
    [Migration("20200918090105_creater")]
    partial class creater
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KlopZavod.Models.Assoc", b =>
                {
                    b.Property<int>("AssocID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jamoat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SocrName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssocID");

                    b.ToTable("Assoc");
                });

            modelBuilder.Entity("KlopZavod.Models.Bunt", b =>
                {
                    b.Property<int>("BuntID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuntID");

                    b.ToTable("Bunt");
                });

            modelBuilder.Entity("KlopZavod.Models.Khojagi", b =>
                {
                    b.Property<int>("KhojagiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AssocID")
                        .HasColumnType("int");

                    b.Property<string>("Director")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ga")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int>("RMA")
                        .HasColumnType("int");

                    b.Property<int?>("RayonID")
                        .HasColumnType("int");

                    b.HasKey("KhojagiID");

                    b.HasIndex("AssocID");

                    b.HasIndex("RayonID");

                    b.ToTable("Khojagi");
                });

            modelBuilder.Entity("KlopZavod.Models.PKvitanciya", b =>
                {
                    b.Property<int>("PKvitanciyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("FizVes")
                        .HasColumnType("int");

                    b.Property<int>("KhojagiID")
                        .HasColumnType("int");

                    b.Property<int>("NomerNakl")
                        .HasColumnType("int");

                    b.Property<int>("NomerPK")
                        .HasColumnType("int");

                    b.Property<int>("PartiyaID")
                        .HasColumnType("int");

                    b.Property<double>("Vlagn")
                        .HasColumnType("float");

                    b.Property<double>("Zasor")
                        .HasColumnType("float");

                    b.HasKey("PKvitanciyaID");

                    b.HasIndex("KhojagiID");

                    b.HasIndex("PartiyaID");

                    b.ToTable("PKvitanciya");
                });

            modelBuilder.Entity("KlopZavod.Models.Partiya", b =>
                {
                    b.Property<int>("PartiyaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuntID")
                        .HasColumnType("int");

                    b.Property<string>("NomerPart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sbor")
                        .HasColumnType("int");

                    b.Property<int>("SemenaID")
                        .HasColumnType("int");

                    b.Property<byte>("Sort")
                        .HasColumnType("tinyint");

                    b.Property<int>("Vid")
                        .HasColumnType("int");

                    b.HasKey("PartiyaID");

                    b.HasIndex("BuntID");

                    b.HasIndex("SemenaID");

                    b.ToTable("Partiya");
                });

            modelBuilder.Entity("KlopZavod.Models.Rayon", b =>
                {
                    b.Property<int>("RayonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RayonID");

                    b.ToTable("Rayon");
                });

            modelBuilder.Entity("KlopZavod.Models.Semena", b =>
                {
                    b.Property<int>("SemenaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SemenaID");

                    b.ToTable("Semena");
                });

            modelBuilder.Entity("KlopZavod.Models.Khojagi", b =>
                {
                    b.HasOne("KlopZavod.Models.Assoc", "Assoc")
                        .WithMany("Khojagis")
                        .HasForeignKey("AssocID");

                    b.HasOne("KlopZavod.Models.Rayon", "Rayon")
                        .WithMany("Khojagis")
                        .HasForeignKey("RayonID");
                });

            modelBuilder.Entity("KlopZavod.Models.PKvitanciya", b =>
                {
                    b.HasOne("KlopZavod.Models.Khojagi", "Khojagi")
                        .WithMany("PKvitanciyas")
                        .HasForeignKey("KhojagiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlopZavod.Models.Partiya", "Partiya")
                        .WithMany("PKvitanciyas")
                        .HasForeignKey("PartiyaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KlopZavod.Models.Partiya", b =>
                {
                    b.HasOne("KlopZavod.Models.Bunt", "Bunt")
                        .WithMany("Partiyas")
                        .HasForeignKey("BuntID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlopZavod.Models.Semena", "Semena")
                        .WithMany("Partiyas")
                        .HasForeignKey("SemenaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
